# Generated by Django 4.2 on 2023-05-02 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='Причина удаления')),
                ('req_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_requests', to='books.book', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос на удаление книги',
                'verbose_name_plural': 'Запросы на удаление книги',
                'ordering': ['-req_date'],
            },
        ),
    ]
